#define INTLED 2 
// 2 è L'USCITA PREDEFINITA DEL LED INTEGRATO SULLE SCHEDE IDEASPARK
// VEDI L'ALTRO MIO PROGETTO DOVE CAMBIANDO L'USCITA SI POSSONO PILOTARE LED ESTERNI

void setup() {
  pinMode(INTLED,OUTPUT);

}
void loop() {
  delay(1000);
  digitalWrite(INTLED,HIGH);
  delay(1000);
  digitalWrite(INTLED,LOW); 

}
